export type Level = 'elementary' | 'middle' | 'high' | 'ap' | 'college' | 'advanced';

export const LEVEL_LABELS: Record<Level, string> = {
  elementary: 'Elementary',
  middle:     'Middle School',
  high:       'High School',
  ap:         'AP / IB',
  college:    'College',
  advanced:   'Advanced',
};

export const LEVEL_ICONS: Record<Level, string> = {
  elementary: '🌱',
  middle:     '📚',
  high:       '🎓',
  ap:         '🏆',
  college:    '🔬',
  advanced:   '🧠',
};

export interface Topic {
  id: string;
  title: string;
  description: string;
  estimatedMinutes: number;
}

export interface Course {
  id: string;
  title: string;
  icon: string;
  color: string;
  bgColor: string;
  level: Level;
  description: string;
  topics: Topic[];
}

// ─── helpers ──────────────────────────────────────────────────────────────────
const t = (id: string, title: string, description: string, mins: number): Topic => ({
  id, title, description, estimatedMinutes: mins,
});

// ─── Curriculum ───────────────────────────────────────────────────────────────
export const CURRICULUM: Course[] = [

  // ── Elementary ──────────────────────────────────────────────────────────────
  {
    id: 'elem-kinder',
    title: 'Kindergarten Math',
    icon: '🔢',
    color: '#FF9F43',
    bgColor: '#FFF5E6',
    level: 'elementary',
    description: 'Numbers, shapes, patterns, and early operations',
    topics: [
      t('count-100',   'Counting to 100',      'Count forward and backward by 1s to 100', 10),
      t('nums-0-20',   'Numbers 0–20',          'Read, write, and represent numbers 0 through 20', 10),
      t('compare-k',   'Comparing numbers',     'Use more/less/equal language and symbols', 10),
      t('add-intro',   'Addition intro',        'Join sets of objects and write addition equations', 10),
      t('sub-intro',   'Subtraction intro',     'Separate sets and write subtraction equations', 10),
      t('shapes-k',    'Shapes',                'Identify and describe 2D and 3D shapes', 10),
      t('meas-k',      'Measurement basics',    'Compare heights, lengths, and weights directly', 10),
      t('classify-k',  'Classifying objects',   'Sort objects by color, shape, size, and function', 10),
      t('patterns-k',  'Sorting & patterns',    'Identify, create, and extend AB and ABC patterns', 10),
      t('bonds-k',     'Number bonds',          'Part-part-whole relationships within 10', 10),
    ],
  },
  {
    id: 'elem-1st',
    title: '1st Grade Math',
    icon: '➕',
    color: '#FF6B6B',
    bgColor: '#FFF0F0',
    level: 'elementary',
    description: 'Addition, subtraction, place value, and measurement',
    topics: [
      t('add-20',      'Addition within 20',            'Strategies for adding two numbers up to 20', 12),
      t('sub-20',      'Subtraction within 20',         'Strategies for subtracting within 20', 12),
      t('pv-tens',     'Place value (tens & ones)',      'Understand tens and ones; compose and decompose numbers', 12),
      t('compare-2d',  'Comparing two-digit numbers',   'Use <, >, = to compare two-digit numbers', 10),
      t('meas-1',      'Measuring lengths',             'Measure with non-standard and standard units', 10),
      t('time-1',      'Time (hours & half-hours)',      'Tell and write time on analog and digital clocks', 10),
      t('data-1',      'Data & graphs',                 'Organize, represent, and interpret data in charts', 12),
      t('geo-1',       'Geometry: 2D & 3D shapes',      'Name, describe, and compose 2D and 3D shapes', 10),
      t('word-1',      'Word problems',                 'Solve add/subtract word problems with unknowns', 12),
      t('skip-1',      'Skip counting',                 'Count by 2s, 5s, and 10s on a number line', 10),
    ],
  },
  {
    id: 'elem-2nd',
    title: '2nd Grade Math',
    icon: '🔄',
    color: '#6C63FF',
    bgColor: '#EEF0FF',
    level: 'elementary',
    description: 'Operations to 1000, money, time, and early multiplication',
    topics: [
      t('add-sub-1000', 'Addition & subtraction to 1000', 'Add and subtract 3-digit numbers with regrouping', 12),
      t('pv-1000',      'Place value to 1000',            'Hundreds, tens, and ones; standard and expanded form', 12),
      t('meas-2',       'Measuring in inches & cm',       'Use rulers and estimate lengths', 10),
      t('time-2',       'Time to nearest 5 minutes',      'Tell time on analog clocks to the nearest 5 min', 10),
      t('money-2',      'Money: coins & bills',           'Count, compare, and make change with money', 12),
      t('graphs-2',     'Bar graphs & line plots',        'Read and make bar graphs and line plots', 12),
      t('even-odd',     'Even & odd numbers',             'Identify even and odd numbers and explain why', 10),
      t('mul-intro',    'Multiplication intro',           'Equal groups and the meaning of multiplication', 12),
      t('arrays-2',     'Arrays & repeated addition',     'Relate arrays to multiplication and addition', 12),
      t('geo-2',        'Geometry: sides & angles',       'Count sides and angles; describe 2D shapes', 10),
    ],
  },
  {
    id: 'elem-3rd',
    title: '3rd Grade Math',
    icon: '✖️',
    color: '#4ECDC4',
    bgColor: '#E8FAF9',
    level: 'elementary',
    description: 'Multiplication, division, fractions, and area',
    topics: [
      t('mul-10',    'Multiplication (1–10)',       'Learn and apply multiplication facts through 10×10', 12),
      t('div-10',    'Division (1–10)',             'Understand division as sharing and repeated subtraction', 12),
      t('frac-nl',   'Fractions on a number line', 'Locate and label unit fractions on a number line', 12),
      t('equiv-3',   'Equivalent fractions',       'Use models to identify and generate equivalent fractions', 12),
      t('comp-frac', 'Comparing fractions',        'Compare fractions with the same numerator or denominator', 12),
      t('area-per',  'Area & perimeter',           'Find area by tiling and perimeter by adding side lengths', 12),
      t('quad-3',    'Quadrilaterals',             'Identify and categorize squares, rectangles, rhombuses', 10),
      t('time-3',    'Telling time & elapsed time','Tell time and solve elapsed time problems', 12),
      t('round-3',   'Rounding numbers',           'Round to the nearest ten and hundred', 12),
      t('word-3',    'Multi-step word problems',   'Solve 2-step problems using all four operations', 15),
    ],
  },
  {
    id: 'elem-4th',
    title: '4th Grade Math',
    icon: '📐',
    color: '#43D9AD',
    bgColor: '#EAFAF6',
    level: 'elementary',
    description: 'Multi-digit operations, fractions, decimals, and angles',
    topics: [
      t('mul-multi',  'Multi-digit multiplication',    'Multiply multi-digit numbers using standard algorithm', 12),
      t('long-div',   'Long division',                 'Divide up to 4-digit dividends by 1-digit divisors', 12),
      t('fact-mult',  'Factors & multiples',           'Find factors, multiples, prime and composite numbers', 12),
      t('frac-add',   'Fraction addition & subtraction','Add and subtract fractions with like denominators', 12),
      t('frac-mul',   'Multiplying fractions',         'Multiply a fraction by a whole number', 12),
      t('dec-100',    'Decimals to hundredths',        'Read, write, and compare decimals to hundredths', 12),
      t('angles-4',   'Angles & protractors',          'Measure and classify angles; draw angles with a protractor', 12),
      t('sym-4',      'Lines of symmetry',             'Identify lines of symmetry in shapes', 10),
      t('conv-4',     'Measurement conversion',        'Convert units within the metric and customary systems', 12),
      t('lplot-4',    'Data: line plots',              'Make and interpret line plots with fractions', 12),
    ],
  },
  {
    id: 'elem-5th',
    title: '5th Grade Math',
    icon: '📊',
    color: '#9B59B6',
    bgColor: '#F5EEF8',
    level: 'elementary',
    description: 'Decimals, fraction division, volume, and coordinate plane',
    topics: [
      t('dec-pv',    'Decimal place value',            'Read, write, and round decimals to thousandths', 12),
      t('dec-ops',   'Multiplying & dividing decimals','Multiply and divide decimals using place value', 12),
      t('frac-div',  'Fraction division',              'Divide fractions and whole numbers by fractions', 12),
      t('pow-10',    'Powers of ten',                  'Multiply and divide by powers of ten; exponent notation', 12),
      t('vol-rect',  'Volume of rectangular prisms',  'Find volume using unit cubes and V = l × w × h', 12),
      t('coord-5',   'The coordinate plane',          'Graph points in the first quadrant; read ordered pairs', 12),
      t('alg-pat',   'Algebraic thinking & patterns', 'Generate and analyze numerical patterns using rules', 12),
      t('conv-5',    'Converting units',              'Convert customary and metric units in multi-step problems', 12),
      t('class-2d',  'Classifying 2D figures',        'Classify polygons by properties in a hierarchy', 10),
      t('lplot-5',   'Line plots with fractions',     'Interpret and create line plots with fractional data', 12),
    ],
  },

  // ── Middle School ────────────────────────────────────────────────────────────
  {
    id: 'mid-6th',
    title: '6th Grade Math',
    icon: '⚖️',
    color: '#FF6B6B',
    bgColor: '#FFF0F0',
    level: 'middle',
    description: 'Ratios, negative numbers, expressions, and statistics',
    topics: [
      t('ratio-6',    'Ratios & proportional relationships', 'Understand ratios and use ratio language', 15),
      t('rate-6',     'Rates & percentages',                 'Unit rates, percent of a number, percent change', 15),
      t('neg-6',      'Negative numbers',                    'Understand and locate negative numbers on a number line', 15),
      t('abs-6',      'Absolute value',                      'Interpret absolute value as distance from zero', 12),
      t('fact-6',     'Factors & multiples',                 'GCF, LCM, and prime factorization', 15),
      t('frac-6',     'Fraction operations',                 'Add, subtract, multiply, and divide fractions', 15),
      t('dec-6',      'Decimal operations',                  'Add, subtract, multiply, and divide decimals', 15),
      t('expr-6',     'Expressions & equations',             'Write and evaluate algebraic expressions; one-step equations', 15),
      t('area-6',     'Area of polygons',                    'Find area of triangles, parallelograms, and composite shapes', 15),
      t('stat-6',     'Statistics & data distributions',     'Mean, median, mode, range, and box plots', 15),
    ],
  },
  {
    id: 'mid-7th',
    title: '7th Grade Math',
    icon: '📈',
    color: '#4ECDC4',
    bgColor: '#E8FAF9',
    level: 'middle',
    description: 'Proportions, rational numbers, geometry, and probability',
    topics: [
      t('prop-7',   'Proportional relationships',          'Identify and represent proportional relationships', 15),
      t('slope-7',  'Slope & y-intercept',                 'Calculate slope and interpret y-intercept', 18),
      t('pct-7',    'Percent problems',                    'Percent increase/decrease, discount, tax, and tip', 15),
      t('int-add',  'Adding & subtracting integers',       'Add and subtract positive and negative integers', 15),
      t('rat-mul',  'Multiplying & dividing rational numbers', 'Multiply and divide fractions including negatives', 15),
      t('eq-ineq',  'Equations & inequalities',            'Solve two-step equations and graph inequalities', 18),
      t('scale-7',  'Geometry: scale & similar figures',   'Scale drawings and properties of similar figures', 15),
      t('circle-7', 'Circle area & circumference',         'Apply C = 2πr and A = πr² in problems', 15),
      t('prob-7',   'Probability',                         'Theoretical and experimental probability; sample spaces', 15),
      t('samp-7',   'Sampling & data',                     'Random samples and drawing inferences about populations', 15),
    ],
  },
  {
    id: 'mid-8th',
    title: '8th Grade Math',
    icon: '🔷',
    color: '#6C63FF',
    bgColor: '#EEF0FF',
    level: 'middle',
    description: 'Linear equations, functions, Pythagorean theorem, and transformations',
    topics: [
      t('lin-8',    'Linear equations',                    'Solve one-variable linear equations with variables on both sides', 18),
      t('sys-8',    'Systems of equations',                'Solve systems by graphing and substitution', 20),
      t('func-8',   'Functions & function notation',       'Understand functions; use function notation f(x)', 18),
      t('exp-8',    'Exponents & scientific notation',     'Integer exponents, laws of exponents, scientific notation', 15),
      t('irr-8',    'Irrational numbers',                  'Approximate square roots and understand π', 15),
      t('pyth-8',   'The Pythagorean theorem',             'Apply a² + b² = c² and its converse', 18),
      t('trans-8',  'Transformations',                     'Translations, reflections, rotations, and dilations on the coordinate plane', 18),
      t('scat-8',   'Scatter plots & line of best fit',    'Interpret scatter plots and draw trend lines', 15),
      t('vol-8',    'Volume of spheres & cylinders',       'Apply volume formulas for 3D solids', 15),
      t('intro-f',  'Introduction to functions',           'Distinguish linear and non-linear functions; interpret graphs', 18),
    ],
  },
  {
    id: 'mid-prealg',
    title: 'Pre-Algebra',
    icon: '𝑥',
    color: '#9B59B6',
    bgColor: '#F5EEF8',
    level: 'middle',
    description: 'Bridge course connecting arithmetic to Algebra 1',
    topics: [
      t('arith-prop', 'Arithmetic properties',        'Commutative, associative, distributive, and identity properties', 15),
      t('fact-pa',    'Factors & multiples',          'Prime factorization, GCF, and LCM', 15),
      t('frac-pa',    'Fractions review',             'All four operations with fractions and mixed numbers', 15),
      t('dec-pa',     'Decimals & place value',       'Operations with decimals; converting fractions and decimals', 15),
      t('neg-pa',     'Negative numbers',             'Operations with positive and negative rational numbers', 15),
      t('ratio-pa',   'Ratios & proportions',         'Set up and solve proportions; unit rate', 15),
      t('alg-pa',     'Intro to algebra',             'Variables, expressions, and one-step equations', 18),
      t('coord-pa',   'Coordinate plane',             'Plot points in all four quadrants; find distance', 15),
      t('eq-pa',      'Equations with one variable',  'Solve two-step equations with integers and fractions', 18),
      t('stat-pa',    'Basic statistics',             'Mean, median, mode, range, and interpreting graphs', 15),
    ],
  },

  // ── High School ──────────────────────────────────────────────────────────────
  {
    id: 'hs-alg1',
    title: 'Algebra 1',
    icon: '𝑓',
    color: '#6C63FF',
    bgColor: '#EEF0FF',
    level: 'high',
    description: 'Equations, functions, and quadratics',
    topics: [
      t('lin-eq',   'Solving linear equations',       'Multi-step equations; variables on both sides; literal equations', 20),
      t('ineq-1',   'Inequalities',                   'Solve and graph linear inequalities; compound inequalities', 20),
      t('sys-1',    'Systems of equations',           'Substitution, elimination, and graphing methods', 22),
      t('func-1',   'Functions',                      'Function definition, notation, domain, range, and representations', 20),
      t('lin-func', 'Linear functions & graphs',      'Slope-intercept, point-slope, standard forms; parallel/perpendicular lines', 22),
      t('quad-1',   'Quadratic equations',            'Solve by factoring, completing the square, and quadratic formula', 25),
      t('fact-1',   'Factoring polynomials',          'GCF, difference of squares, perfect square trinomials, and ax²+bx+c', 22),
      t('exp-1',    'Exponential functions',          'Growth and decay models; evaluating and graphing exponentials', 20),
      t('stat-1',   'Statistics & probability',       'Data displays, measures of center, and basic probability', 18),
      t('seq-1',    'Sequences',                      'Arithmetic and geometric sequences; recursive and explicit formulas', 20),
    ],
  },
  {
    id: 'hs-geo',
    title: 'Geometry',
    icon: '△',
    color: '#4ECDC4',
    bgColor: '#E8FAF9',
    level: 'high',
    description: 'Proof, congruence, similarity, and measurement',
    topics: [
      t('trans-g',  'Geometric transformations',          'Translations, reflections, rotations, and dilations', 20),
      t('cong-g',   'Congruence & similarity',            'SSS/SAS/ASA/AAS congruence; AA/SSS/SAS similarity', 22),
      t('proof-g',  'Proofs & reasoning',                 'Two-column proofs, paragraph proofs, and flow proofs', 22),
      t('tri-g',    'Triangle properties',                'Triangle sum, exterior angle, midsegment, and inequalities', 20),
      t('para-g',   'Parallelograms',                     'Properties of parallelograms, rectangles, rhombuses, and squares', 20),
      t('pyth-g',   'Pythagorean theorem',                'Pythagorean theorem, converse, and special right triangles (30-60-90, 45-45-90)', 20),
      t('circ-g',   'Circles',                            'Central angles, arcs, chords, tangents, and inscribed angles', 22),
      t('trig-g',   'Trigonometric ratios (SOH-CAH-TOA)', 'sin, cos, tan in right triangles; solving for sides and angles', 22),
      t('area-g',   'Area & volume',                      'Area of polygons and circles; surface area and volume of solids', 20),
      t('coord-g',  'Coordinate geometry',                'Distance, midpoint, slope, equations of lines and circles', 20),
    ],
  },
  {
    id: 'hs-alg2',
    title: 'Algebra 2',
    icon: '√',
    color: '#FF6B6B',
    bgColor: '#FFF0F0',
    level: 'high',
    description: 'Advanced functions, complex numbers, and conic sections',
    topics: [
      t('poly-2',    'Polynomial arithmetic',                  'Add, subtract, multiply, and divide polynomials', 20),
      t('fact-div',  'Factoring & polynomial division',        'Factor completely; long and synthetic division; factor theorem', 22),
      t('rat-2',     'Rational functions',                     'Simplify, add/subtract, and multiply/divide rational expressions', 22),
      t('rad-2',     'Radical functions',                      'Simplify radicals; solve radical equations; nth roots', 20),
      t('comp-2',    'Complex numbers',                        'Imaginary unit, operations in rectangular form, and the complex plane', 20),
      t('disc-2',    'Quadratic formula & the discriminant',   'Derive the quadratic formula; interpret the discriminant', 20),
      t('explog-2',  'Exponential & logarithmic functions',    'Graph, transform, and solve equations; natural log and base-e', 22),
      t('trig-2',    'Trigonometric functions',                'Unit circle, radians, graphs of sin/cos/tan and their inverses', 25),
      t('conic-2',   'Conic sections',                        'Parabolas, ellipses, hyperbolas, and circles in standard form', 22),
      t('series-2',  'Series & sequences',                     'Arithmetic and geometric series; sigma notation; sum formulas', 20),
    ],
  },
  {
    id: 'hs-precalc',
    title: 'Precalculus',
    icon: '→',
    color: '#9B59B6',
    bgColor: '#F5EEF8',
    level: 'high',
    description: 'Advanced functions, vectors, matrices, and limits',
    topics: [
      t('comp-pc',   'Composite & inverse functions',      'Composition (f∘g), inverse functions, and one-to-one tests', 22),
      t('poly-pc',   'Polynomial & rational functions',    'Zeros, end behavior, asymptotes, rational zeros theorem', 22),
      t('comp-pc2',  'Complex numbers',                    'Operations, polar form, and De Moivre\'s theorem', 20),
      t('conic-pc',  'Conic sections',                     'Derive and apply standard-form equations; foci and directrix', 22),
      t('mat-pc',    'Matrices',                           'Matrix operations, determinants, inverses, and linear systems', 22),
      t('vec-pc',    'Vectors',                            '2D and 3D vectors; dot product, magnitude, and direction', 22),
      t('param-pc',  'Parametric equations',               'Graph and convert parametric curves; eliminate the parameter', 20),
      t('polar-pc',  'Polar coordinates',                  'Convert between polar and rectangular; graph polar curves', 20),
      t('comb-pc',   'Probability & combinatorics',        'Fundamental counting, permutations, combinations, and probability', 20),
      t('lim-pc',    'Intro to limits',                    'Intuitive limits, one-sided limits, and continuity', 22),
    ],
  },
  {
    id: 'hs-stats',
    title: 'Statistics (HS)',
    icon: '📊',
    color: '#FFB84D',
    bgColor: '#FFF8EC',
    level: 'high',
    description: 'Data analysis, probability, and statistical inference',
    topics: [
      t('disp-s',  'Displaying & comparing data',     'Dot plots, histograms, box plots; comparing distributions', 20),
      t('norm-s',  'Normal distributions',            'Properties of normal curves; z-scores; 68-95-99.7 rule', 22),
      t('prob-s',  'Probability rules',               'Addition rule, multiplication rule, complement rule', 20),
      t('cond-s',  'Conditional probability',         'Conditional probability, independence, and two-way tables', 22),
      t('binom-s', 'Binomial distributions',          'Binomial setting, formula, mean, and standard deviation', 22),
      t('samp-s',  'Sampling methods',                'SRS, stratified, cluster; bias and sampling variability', 18),
      t('ci-s',    'Confidence intervals',            'Interpret and construct confidence intervals for proportions and means', 22),
      t('hyp-s',   'Hypothesis testing',              'Null/alternative hypotheses; p-values; Type I and II errors', 22),
      t('chi-s',   'Chi-square tests',                'Goodness of fit and test for independence', 22),
      t('reg-s',   'Regression & correlation',        'Least-squares regression line; r and r²; residuals', 22),
    ],
  },

  // ── AP / IB ─────────────────────────────────────────────────────────────────
  {
    id: 'ap-calcab',
    title: 'AP Calculus AB',
    icon: '∂',
    color: '#FF6B6B',
    bgColor: '#FFF0F0',
    level: 'ap',
    description: 'Limits, derivatives, and definite integrals (AP exam)',
    topics: [
      t('lim-ab',   'Limits & continuity',                 'Limit laws, squeeze theorem, types of discontinuity', 28),
      t('def-ab',   'Definition of the derivative',        'Limit definition, instantaneous rate of change, tangent lines', 28),
      t('rules-ab', 'Differentiation rules',               'Power, constant, sum, difference rules; higher-order derivatives', 25),
      t('chain-ab', 'Chain rule',                          'Differentiate composite functions; chain rule applications', 25),
      t('impl-ab',  'Implicit differentiation',            'Differentiate implicitly; find dy/dx for implicitly defined curves', 25),
      t('trig-ab',  'Derivatives of trig, log & exp',      'Derivatives of sin, cos, tan, ln, eˣ, aˣ, logₐ', 25),
      t('mvt-ab',   'Mean value theorem',                  'Rolle\'s theorem, MVT, and consequences', 25),
      t('sketch-ab','Curve sketching',                     'Critical points, first/second derivative tests, concavity', 28),
      t('opt-ab',   'Optimization',                        'Closed interval method; applied optimization problems', 28),
      t('indef-ab', 'Definite & indefinite integrals',     'Antiderivatives; Riemann sums; definite integral as limit', 28),
      t('ftc-ab',   'Fundamental theorem of calculus',     'FTC Parts 1 and 2; accumulation functions', 28),
      t('usub-ab',  'u-substitution',                      'Change of variable technique for indefinite and definite integrals', 25),
      t('de-ab',    'Differential equations (basic)',      'Slope fields; separation of variables; exponential growth/decay', 25),
      t('area-ab',  'Area between curves',                 'Set up and evaluate integrals for area between two curves', 28),
      t('vol-ab',   'Volumes of revolution',               'Disk and washer methods about x- and y-axes', 28),
    ],
  },
  {
    id: 'ap-calcbc',
    title: 'AP Calculus BC',
    icon: '∫',
    color: '#6C63FF',
    bgColor: '#EEF0FF',
    level: 'ap',
    description: 'All AB topics plus series, parametric, and polar (AP exam)',
    topics: [
      t('ibp-bc',   'Integration by parts',              '∫u dv = uv − ∫v du; tabular method', 28),
      t('pf-bc',    'Partial fractions',                 'Decompose rational functions; integrate each term', 28),
      t('imp-bc',   'Improper integrals',                'Limits of integration at infinity or discontinuity', 25),
      t('pv-bc',    'Parametric & vector functions',     'Derivatives and arc length for parametric curves; vector-valued functions', 28),
      t('pol-bc',   'Polar curves',                      'Graph polar curves; area and arc length in polar form', 28),
      t('seq-bc',   'Infinite sequences & series',       'Convergence of sequences; series definition and partial sums', 28),
      t('tay-bc',   'Taylor & Maclaurin series',         'Derive Taylor series; error bounds', 30),
      t('conv-bc',  'Convergence tests',                 'Integral, comparison, limit comparison, ratio, alternating series tests', 28),
      t('log-bc',   'Logistic differential equations',  'Logistic growth model; solving and interpreting solutions', 25),
      t('all-ab',   'All AB Topics (Review)',            'Complete review of limits, derivatives, and basic integration', 25),
    ],
  },
  {
    id: 'ap-stats',
    title: 'AP Statistics',
    icon: '📉',
    color: '#43D9AD',
    bgColor: '#EAFAF6',
    level: 'ap',
    description: 'Rigorous data analysis and inference (AP exam)',
    topics: [
      t('dist-as',  'Exploring data distributions',    'Shape, center, spread; outliers; frequency and relative frequency', 25),
      t('biv-as',   'Bivariate data & regression',     'Scatterplots, correlation, LSRL, residuals, and transformations', 25),
      t('des-as',   'Designing studies',               'Observational studies, experiments, randomization, and blocking', 22),
      t('samp-as',  'Sampling distributions',          'Sampling distribution of x̄ and p̂; CLT; standard error', 25),
      t('prob-as',  'Probability',                     'Event rules, conditional probability, random variables, expected value', 25),
      t('inf-p-as', 'Inference for proportions',       'One- and two-proportion z-tests and confidence intervals', 25),
      t('inf-m-as', 'Inference for means',             'One- and two-sample t-tests and t-intervals', 25),
      t('chi-as',   'Chi-square tests',                'GOF, homogeneity, and independence tests', 25),
      t('reg-as',   'Inference for regression',        't-test for slope; confidence interval for slope', 25),
      t('sim-as',   'Simulation & randomization',      'Use simulation to approximate p-values and sampling distributions', 22),
    ],
  },

  // ── College ──────────────────────────────────────────────────────────────────
  {
    id: 'col-calc1',
    title: 'Calculus 1',
    icon: '∂',
    color: '#6C63FF',
    bgColor: '#EEF0FF',
    level: 'college',
    description: 'Limits, derivatives, integrals, and applications',
    topics: [
      t('lim-c1',   'Limits & continuity',                   'Epsilon-delta, limit laws, one-sided limits, squeeze theorem', 30),
      t('drules-c1','Derivative rules',                      'Power, product, quotient, chain; trig, exp, and log derivatives', 28),
      t('impl-c1',  'Implicit differentiation',              'Differentiate implicitly; find tangent lines to implicit curves', 25),
      t('rr-c1',    'Related rates',                         'Model rates of change in dynamic geometric situations', 28),
      t('lh-c1',    "L'Hôpital's rule",                      'Apply L\'Hôpital to 0/0, ∞/∞, and other indeterminate forms', 25),
      t('cs-c1',    'Curve sketching & optimization',        'First/second derivative tests, concavity, EVT, applied optimization', 30),
      t('rs-c1',    'Riemann sums',                          'Left, right, midpoint, and trapezoidal approximations', 25),
      t('def-c1',   'Definite integrals',                    'Definition as limit of Riemann sum; properties of definite integrals', 28),
      t('ftc-c1',   'Fundamental theorem of calculus',       'FTC 1 and 2; antiderivatives; net change theorem', 28),
      t('usub-c1',  'u-substitution',                        'Substitution technique for indefinite and definite integrals', 25),
      t('area-c1',  'Area & net change',                     'Area between curves; net change from rate of change', 28),
    ],
  },
  {
    id: 'col-calc2',
    title: 'Calculus 2',
    icon: '∫',
    color: '#FF6B6B',
    bgColor: '#FFF0F0',
    level: 'college',
    description: 'Advanced integration techniques and infinite series',
    topics: [
      t('ibp-c2',  'Integration by parts',               'Formula ∫u dv; tabular integration; reduction formulas', 28),
      t('trig-c2', 'Trigonometric integrals',            'Powers of sin and cos; trig substitution', 28),
      t('pf-c2',   'Partial fractions',                  'Decompose proper rational functions; integrate each term', 28),
      t('imp-c2',  'Improper integrals',                 'Type I (infinite limits) and Type II (discontinuities); comparison test', 25),
      t('de-c2',   'Differential equations',             'Separable equations; exponential growth/decay; logistic models', 28),
      t('seq-c2',  'Sequences & series',                 'Convergence; geometric, p-series; divergence test', 28),
      t('tay-c2',  'Taylor & Maclaurin series',          'Taylor polynomial; Taylor series; error estimation', 30),
      t('ps-c2',   'Power series',                       'Radius and interval of convergence; differentiation and integration of power series', 28),
      t('param-c2','Parametric curves',                  'Derivatives, arc length, and area for parametric equations', 25),
      t('polar-c2','Polar coordinates',                  'Convert coordinates; graph polar curves; area and arc length in polar', 25),
    ],
  },
  {
    id: 'col-calc3',
    title: 'Multivariable Calculus',
    icon: '∇',
    color: '#4ECDC4',
    bgColor: '#E8FAF9',
    level: 'college',
    description: 'Calculus extended to functions of several variables',
    topics: [
      t('vec-c3',   'Vectors in 3D',                         'Vector algebra; magnitude and direction; unit vectors', 30),
      t('dot-c3',   'Dot & cross products',                  'Dot product (angle, projection); cross product (area, torque)', 30),
      t('lp-c3',    'Lines & planes in space',               'Parametric equations of lines; normal vectors and equations of planes', 28),
      t('pd-c3',    'Partial derivatives',                   'Compute partial derivatives; higher-order partials; mixed partials', 30),
      t('grad-c3',  'Gradient & directional derivatives',    'Gradient vector; maximum rate of change; level curves', 30),
      t('lag-c3',   'Lagrange multipliers',                  'Constrained optimization using Lagrange multipliers', 30),
      t('dbl-c3',   'Double & triple integrals',             'Fubini\'s theorem; switching order; polar, cylindrical, spherical coords', 32),
      t('jac-c3',   'Change of variables (Jacobian)',        'Jacobian determinant; change of variables in multiple integrals', 28),
      t('li-c3',    'Line integrals',                        'Scalar and vector line integrals; work and circulation', 30),
      t('green-c3', "Green's theorem",                       'Relate line integrals to double integrals over a region', 30),
      t('surf-c3',  'Surface integrals',                     'Parametrize surfaces; flux integrals', 30),
      t('stokes-c3', "Stokes' & divergence theorems",        'Stokes\' theorem; Gauss\'s divergence theorem; applications', 32),
    ],
  },
  {
    id: 'col-linalg',
    title: 'Linear Algebra',
    icon: '[A]',
    color: '#FFB84D',
    bgColor: '#FFF8EC',
    level: 'college',
    description: 'Vectors, matrices, and linear transformations',
    topics: [
      t('vs-la',   'Vectors & vector spaces',         'Vector axioms; subspaces; span and linear independence', 30),
      t('mat-la',  'Matrix operations',               'Addition, scalar multiplication, matrix multiplication, transpose', 28),
      t('gauss-la','Gaussian elimination',            'Row operations; reduced row echelon form; solving linear systems', 30),
      t('det-la',  'Determinants',                    'Cofactor expansion; properties; Cramer\'s rule', 28),
      t('inv-la',  'Invertible matrices',             'Conditions for invertibility; finding A⁻¹; the Invertible Matrix Theorem', 28),
      t('lt-la',   'Linear transformations',          'Definition; matrix representation; kernel and image', 30),
      t('eigen-la','Eigenvalues & eigenvectors',      'Characteristic polynomial; finding eigenvalues and eigenvectors', 30),
      t('diag-la', 'Diagonalization',                 'Diagonalize matrices; powers of matrices; spectral theorem', 28),
      t('orth-la', 'Orthogonality & projections',     'Orthogonal sets; Gram-Schmidt; projections onto subspaces', 30),
      t('gram-la', 'Gram-Schmidt process',            'Orthonormalize a basis; QR factorization', 28),
      t('svd-la',  'Singular value decomposition',    'SVD; pseudoinverse; least-squares solutions', 32),
      t('app-la',  'Applications: PCA & Markov chains', 'Principal component analysis and Markov chain steady states', 28),
    ],
  },
  {
    id: 'col-diffeq',
    title: 'Differential Equations',
    icon: "y'",
    color: '#9B59B6',
    bgColor: '#F5EEF8',
    level: 'college',
    description: 'Solving and analyzing ordinary differential equations',
    topics: [
      t('fo-de',  'First-order ODEs',                  'Direction fields; existence and uniqueness theorem', 30),
      t('sep-de', 'Separable equations',               'Solve by separating variables and integrating both sides', 28),
      t('lin-de', 'Linear first-order equations',      'Integrating factor method; solve y\' + P(x)y = Q(x)', 28),
      t('exact-de','Exact equations',                  'Test for exactness; potential function method', 28),
      t('num-de',  'Numerical methods (Euler)',        'Euler\'s method; improved Euler; error analysis', 25),
      t('so-de',   'Second-order linear ODEs',         'Homogeneous equations; characteristic equation; Wronskian', 30),
      t('char-de', 'Characteristic equation',         'Real, complex, and repeated roots; general solutions', 28),
      t('uc-de',   'Undetermined coefficients',        'Particular solutions for polynomial, exponential, and trig forcing', 28),
      t('vp-de',   'Variation of parameters',          'General method for particular solutions when UCC fails', 28),
      t('lap-de',  'Laplace transforms',               'Definition, table, properties; inverse Laplace; solving IVPs', 32),
      t('sys-de',  'Systems of ODEs',                  'Matrix form; eigenvalue method for systems; phase portraits', 30),
      t('phase-de','Phase planes & stability',          'Equilibria; stability analysis; predator-prey systems', 30),
    ],
  },
  {
    id: 'col-probstat',
    title: 'Probability & Statistics',
    icon: '🎲',
    color: '#43D9AD',
    bgColor: '#EAFAF6',
    level: 'college',
    description: 'Probability theory and statistical inference',
    topics: [
      t('samp-ps',  'Sample spaces & events',                     'Set notation, events, classical and axiomatic probability', 25),
      t('cond-ps',  'Conditional probability',                    'Conditional probability; multiplication rule; independence', 25),
      t('bayes-ps', "Bayes' theorem",                             'Total probability law and Bayes\' formula with applications', 25),
      t('rv-ps',    'Random variables (discrete & continuous)',    'PMF, PDF, CDF; discrete vs continuous RVs', 28),
      t('exp-ps',   'Expectation & variance',                     'E[X], Var[X], standard deviation; linearity of expectation', 28),
      t('dist-ps',  'Binomial, Poisson & geometric distributions','Derive formulas; compute probabilities; identify the distribution', 28),
      t('norm-ps',  'Normal & exponential distributions',         'Normal distribution, z-scores; exponential distribution and memoryless property', 28),
      t('clt-ps',   'Central limit theorem',                      'Statement and applications; sampling distribution of the mean', 28),
      t('est-ps',   'Point estimation',                           'MLE, method of moments; unbiasedness and efficiency', 28),
      t('ci-ps',    'Confidence intervals',                       'Z and t intervals; interpreting confidence intervals', 28),
      t('hyp-ps',   'Hypothesis testing',                         'Test statistic, p-value, power; one- and two-sided tests', 28),
      t('reg-ps',   'Regression analysis',                        'Simple linear regression; inference for regression; residual analysis', 28),
    ],
  },

  // ── Advanced ─────────────────────────────────────────────────────────────────
  {
    id: 'adv-numthry',
    title: 'Number Theory',
    icon: 'ℤ',
    color: '#FF9F43',
    bgColor: '#FFF5E6',
    level: 'advanced',
    description: 'Deep properties of integers, primes, and congruences',
    topics: [
      t('div-nt',   'Divisibility & primes',               'Divisibility rules; infinitely many primes; prime gaps', 35),
      t('fta-nt',   'Fundamental theorem of arithmetic',   'Unique prime factorization; proof and applications', 35),
      t('gcd-nt',   'GCD & LCM',                           'Properties of GCD and LCM; relationship between them', 30),
      t('eucl-nt',  'Euclidean algorithm',                 'Euclidean algorithm; extended Euclidean algorithm; Bézout\'s identity', 35),
      t('mod-nt',   'Modular arithmetic',                  'Congruence classes; modular addition, multiplication, and exponentiation', 35),
      t('cong-nt',  'Congruences',                         'Linear congruences; solving ax ≡ b (mod n)', 35),
      t('fer-nt',   "Fermat's little theorem",             'Statement and proof; applications to primality and computation', 35),
      t('crt-nt',   'Chinese remainder theorem',           'Statement, proof, and algorithm; applications', 35),
      t('prim-nt',  'Primitive roots',                     'Order of an element; primitive roots; discrete logarithm', 38),
      t('qr-nt',    'Quadratic residues',                  'Legendre symbol; quadratic reciprocity law', 38),
      t('dioph-nt', 'Diophantine equations',               'Linear Diophantine equations; Pell\'s equation; Pythagorean triples', 38),
      t('dist-nt',  'Prime counting & distribution',       'π(x); prime number theorem; Bertrand\'s postulate', 38),
    ],
  },
  {
    id: 'adv-comb',
    title: 'Combinatorics',
    icon: '🔀',
    color: '#6C63FF',
    bgColor: '#EEF0FF',
    level: 'advanced',
    description: 'Counting, graph theory, and combinatorial structures',
    topics: [
      t('count-co',  'Counting principles',            'Sum rule, product rule, bijective proofs', 30),
      t('perm-co',   'Permutations & combinations',    'P(n,k) and C(n,k); circular permutations', 30),
      t('binom-co',  'Binomial theorem',               'Binomial expansion; Pascal\'s triangle; identities', 32),
      t('pig-co',    'Pigeonhole principle',           'Basic and generalized pigeonhole principle with applications', 32),
      t('ie-co',     'Inclusion-exclusion',            'Principle of inclusion-exclusion; Euler\'s totient function', 32),
      t('gen-co',    'Generating functions',           'Ordinary and exponential generating functions', 35),
      t('rec-co',    'Recurrence relations',           'Solving linear recurrences; characteristic polynomial method', 35),
      t('graph-co',  'Graph theory basics',            'Paths, cycles, trees, graph coloring, and planarity', 35),
      t('ram-co',    'Ramsey theory intro',            'Ramsey numbers; party problem; complete subgraphs', 38),
      t('prob-co',   'Probability combinatorics',      'Probabilistic method; random graphs', 35),
      t('stars-co',  'Stars & bars',                  'Distributing indistinguishable objects; non-negative integer solutions', 30),
      t('dbl-co',    'Double counting',               'Proving identities by counting a set two ways', 32),
    ],
  },
  {
    id: 'adv-realana',
    title: 'Real Analysis',
    icon: 'ℝ',
    color: '#FF6B6B',
    bgColor: '#FFF0F0',
    level: 'advanced',
    description: 'Rigorous foundations of calculus and the real number system',
    topics: [
      t('axiom-ra', 'Axioms of the reals',              'Ordered field axioms; completeness axiom; Archimedean property', 35),
      t('seq-ra',   'Sequences & limits',               'Epsilon-N definition of limit; limit laws; monotone convergence', 35),
      t('bw-ra',    'Bolzano-Weierstrass theorem',      'Every bounded sequence has a convergent subsequence; proof', 35),
      t('ser-ra',   'Series convergence',               'Cauchy criterion; absolute convergence; rearrangement theorem', 35),
      t('cont-ra',  'Continuity & uniform continuity',  'ε-δ definition; properties; uniform continuity theorem', 35),
      t('diff-ra',  'Differentiation (rigorous)',       'Differentiability implies continuity; mean value theorem proof', 35),
      t('riem-ra',  'Riemann integration',              'Darboux sums; Riemann integrability; integrable functions', 38),
      t('ftcr-ra',  'Fundamental theorem (rigorous)',   'Proofs of FTC Parts 1 and 2', 35),
      t('metric-ra','Metric spaces',                    'Definition, open and closed sets, convergence, completeness', 38),
      t('comp-ra',  'Compactness',                      'Sequential and open cover compactness; Heine-Borel theorem', 38),
      t('conn-ra',  'Connectedness',                    'Connected sets; intermediate value theorem from connectedness', 35),
      t('unif-ra',  'Uniform convergence',              'Pointwise vs uniform convergence; continuity and integration of limits', 38),
    ],
  },
  {
    id: 'adv-absalg',
    title: 'Abstract Algebra',
    icon: '⊕',
    color: '#43D9AD',
    bgColor: '#EAFAF6',
    level: 'advanced',
    description: 'Groups, rings, fields, and their structures',
    topics: [
      t('grp-aa',   'Groups & group axioms',              'Definition, examples, and basic properties of groups', 35),
      t('sub-aa',   'Subgroups & Lagrange\'s theorem',    'Subgroup criteria; cosets; Lagrange\'s theorem', 35),
      t('cyc-aa',   'Cyclic groups',                      'Generators; order of elements; cyclic group classification', 35),
      t('hom-aa',   'Homomorphisms & isomorphisms',       'Kernel and image; first isomorphism theorem', 38),
      t('quot-aa',  'Quotient groups',                    'Normal subgroups; quotient group construction; examples', 35),
      t('ring-aa',  'Rings & ideals',                     'Ring axioms; ring homomorphisms; ideals; quotient rings', 35),
      t('dom-aa',   'Integral domains',                   'Cancellation; field of fractions; unique factorization domains', 35),
      t('field-aa', 'Fields',                             'Field axioms; finite fields; characteristic', 35),
      t('poly-aa',  'Polynomial rings',                   'Division algorithm; irreducibility; factorization in F[x]', 35),
      t('gal-aa',   'Galois theory intro',                'Splitting fields; Galois group; fundamental theorem of Galois theory', 42),
      t('ext-aa',   'Field extensions',                   'Algebraic and transcendental extensions; degree of extension', 38),
      t('app-aa',   'Applications to geometry & coding', 'Geometric constructions; error-correcting codes; Reed-Solomon', 35),
    ],
  },
  {
    id: 'adv-topo',
    title: 'Topology',
    icon: '∞',
    color: '#9B59B6',
    bgColor: '#F5EEF8',
    level: 'advanced',
    description: 'Topological spaces, continuity, and topological invariants',
    topics: [
      t('ts-to',   'Topological spaces',          'Definition; examples (discrete, indiscrete, metric topology)', 35),
      t('oc-to',   'Open & closed sets',          'Properties; closure; interior; boundary', 35),
      t('cont-to', 'Continuity in topology',      'Continuous functions; homeomorphisms; sequential continuity', 35),
      t('homeo-to','Homeomorphisms',              'Definition; topological invariants; examples', 35),
      t('conn-to', 'Connectedness',              'Path-connected vs connected; connected components', 35),
      t('comp-to', 'Compactness',                'Open cover definition; sequential compactness; Tychonoff theorem', 38),
      t('metric-to','Metric spaces',             'Metric topology; completeness; Baire category theorem', 35),
      t('haus-to', 'Hausdorff spaces',           'Separation axioms; T₁, T₂ spaces; consequences', 35),
      t('fund-to', 'Fundamental group',          'Homotopy; fundamental group π₁; Van Kampen\'s theorem', 40),
      t('cov-to',  'Covering spaces',            'Covering maps; universal cover; lifting theorem', 40),
      t('euler-to','Euler characteristic',       'Euler characteristic for surfaces; classification theorem', 38),
      t('surf-to', 'Surface classification',     'Orientable and non-orientable surfaces; connected sum', 38),
    ],
  },
  {
    id: 'adv-compana',
    title: 'Complex Analysis',
    icon: 'ℂ',
    color: '#FFB84D',
    bgColor: '#FFF8EC',
    level: 'advanced',
    description: 'Analytic functions, contour integration, and residues',
    topics: [
      t('cn-ca',   'Complex numbers & the plane',     'Modulus, argument, Euler\'s formula; geometry of ℂ', 32),
      t('anal-ca', 'Analytic functions',               'Holomorphic functions; Cauchy-Riemann as sufficient condition', 35),
      t('cr-ca',   'Cauchy-Riemann equations',         'Necessary and sufficient conditions for analyticity', 35),
      t('ci-ca',   'Complex integration',              'Contour integrals; parameterization; ML inequality', 35),
      t('cit-ca',  'Cauchy\'s integral theorem',       'Simply connected domains; Cauchy-Goursat theorem', 38),
      t('cif-ca',  'Cauchy\'s integral formula',       'Formula and consequences; higher-order derivatives', 38),
      t('ts-ca',   'Taylor & Laurent series',          'Power series representation; Laurent series and annular regions', 38),
      t('res-ca',  'Residues & poles',                 'Classification of singularities; computing residues', 38),
      t('rt-ca',   'Residue theorem',                  'Application to contour integrals and real integrals', 40),
      t('conf-ca', 'Conformal mappings',               'Angle-preserving maps; Möbius transformations; applications', 38),
      t('mob-ca',  'Möbius transformations',           'Cross-ratio; fixed points; mapping circles to circles', 38),
      t('rmt-ca',  'Riemann mapping theorem',          'Statement and significance; uniformization theorem', 40),
    ],
  },
];
