// USER and STATS are now derived from real saved scan data — see store/savedProblems.tsx

export const TOPICS = [
  {
    id: '1',
    name: 'Algebra',
    icon: '𝑥',
    color: '#6C63FF',
    bgColor: '#EEF0FF',
    progress: 72,
    totalLessons: 24,
    completedLessons: 17,
    description: 'Equations, inequalities, and functions',
  },
  {
    id: '2',
    name: 'Geometry',
    icon: '△',
    color: '#4ECDC4',
    bgColor: '#E8FAF9',
    progress: 45,
    totalLessons: 18,
    completedLessons: 8,
    description: 'Shapes, angles, and spatial reasoning',
  },
  {
    id: '3',
    name: 'Calculus',
    icon: '∫',
    color: '#FF6B6B',
    bgColor: '#FFF0F0',
    progress: 30,
    totalLessons: 30,
    completedLessons: 9,
    description: 'Limits, derivatives, and integrals',
  },
  {
    id: '4',
    name: 'Statistics',
    icon: '📊',
    color: '#FFB84D',
    bgColor: '#FFF8EC',
    progress: 60,
    totalLessons: 16,
    completedLessons: 10,
    description: 'Probability, data, and distributions',
  },
  {
    id: '5',
    name: 'Trigonometry',
    icon: '∿',
    color: '#43D9AD',
    bgColor: '#EAFAF6',
    progress: 15,
    totalLessons: 20,
    completedLessons: 3,
    description: 'Sine, cosine, tangent, and beyond',
  },
  {
    id: '6',
    name: 'Arithmetic',
    icon: '±',
    color: '#9B59B6',
    bgColor: '#F5EEF8',
    progress: 95,
    totalLessons: 12,
    completedLessons: 11,
    description: 'Number theory and operations',
  },
];

// SAVED_PROBLEMS replaced by real data — see store/savedProblems.tsx

export const LESSONS = [
  {
    id: '1',
    topicId: '1',
    topic: 'Algebra',
    topicColor: '#6C63FF',
    topicBg: '#EEF0FF',
    title: 'Quadratic Equations',
    subtitle: '5 lessons · 45 min',
    completed: true,
  },
  {
    id: '2',
    topicId: '1',
    topic: 'Algebra',
    topicColor: '#6C63FF',
    topicBg: '#EEF0FF',
    title: 'Linear Inequalities',
    subtitle: '4 lessons · 30 min',
    completed: true,
  },
  {
    id: '3',
    topicId: '1',
    topic: 'Algebra',
    topicColor: '#6C63FF',
    topicBg: '#EEF0FF',
    title: 'Systems of Equations',
    subtitle: '6 lessons · 55 min',
    completed: false,
  },
  {
    id: '4',
    topicId: '2',
    topic: 'Geometry',
    topicColor: '#4ECDC4',
    topicBg: '#E8FAF9',
    title: 'Triangles & Congruence',
    subtitle: '5 lessons · 50 min',
    completed: true,
  },
  {
    id: '5',
    topicId: '2',
    topic: 'Geometry',
    topicColor: '#4ECDC4',
    topicBg: '#E8FAF9',
    title: 'Circle Theorems',
    subtitle: '4 lessons · 40 min',
    completed: false,
  },
  {
    id: '6',
    topicId: '3',
    topic: 'Calculus',
    topicColor: '#FF6B6B',
    topicBg: '#FFF0F0',
    title: 'Limits & Continuity',
    subtitle: '6 lessons · 60 min',
    completed: true,
  },
  {
    id: '7',
    topicId: '3',
    topic: 'Calculus',
    topicColor: '#FF6B6B',
    topicBg: '#FFF0F0',
    title: 'Differentiation Rules',
    subtitle: '7 lessons · 70 min',
    completed: false,
  },
  {
    id: '8',
    topicId: '4',
    topic: 'Statistics',
    topicColor: '#FFB84D',
    topicBg: '#FFF8EC',
    title: 'Probability Basics',
    subtitle: '4 lessons · 35 min',
    completed: true,
  },
];

export const QUIZ_CATEGORIES = [
  {
    id: '1',
    topic: 'Algebra',
    color: '#6C63FF',
    bgColor: '#EEF0FF',
    icon: '𝑥',
    questions: 20,
    avgTime: '15 min',
    bestScore: 90,
  },
  {
    id: '2',
    topic: 'Geometry',
    color: '#4ECDC4',
    bgColor: '#E8FAF9',
    icon: '△',
    questions: 15,
    avgTime: '12 min',
    bestScore: 73,
  },
  {
    id: '3',
    topic: 'Calculus',
    color: '#FF6B6B',
    bgColor: '#FFF0F0',
    icon: '∫',
    questions: 25,
    avgTime: '20 min',
    bestScore: 68,
  },
  {
    id: '4',
    topic: 'Statistics',
    color: '#FFB84D',
    bgColor: '#FFF8EC',
    icon: '📊',
    questions: 18,
    avgTime: '14 min',
    bestScore: 85,
  },
];

export const RECENT_QUIZZES = [
  {
    id: '1',
    topic: 'Algebra',
    topicColor: '#6C63FF',
    score: 90,
    total: 20,
    date: 'Today',
    time: '13 min',
  },
  {
    id: '2',
    topic: 'Statistics',
    topicColor: '#FFB84D',
    score: 85,
    total: 18,
    date: 'Yesterday',
    time: '11 min',
  },
  {
    id: '3',
    topic: 'Geometry',
    topicColor: '#4ECDC4',
    score: 73,
    total: 15,
    date: '3 days ago',
    time: '14 min',
  },
];

// PROBLEM_OF_THE_DAY and RECENT_ACTIVITY removed — replaced by real saved scan data
